   
name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  test_lint:
    runs-on: ubuntu-latest
    if: ${{ !github.event.created && github.repository != 'garronej/denoify_ci' }}
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-node@v2.1.3
    - name: Making sure 'npm run lint' and 'npm run format' does not changes anything.
      run: |
        PACKAGE_MANAGER=npm
        if [ -f "./yarn.lock" ]; then
            PACKAGE_MANAGER=yarn
        fi
        if [ "$PACKAGE_MANAGER" = "yarn" ]; then
            yarn install --frozen-lockfile                                                                                                                                                                                        
        else
            npm ci
        fi
        $PACKAGE_MANAGER run lint:check
        $PACKAGE_MANAGER run format:check
  test_node:
    runs-on: ${{ matrix.os }}
    needs: test_lint
    strategy:
      matrix:
        node: [ '15', '14', '13', '12' ]
        os: [ windows-latest, ubuntu-latest ]
    name: Test with Node v${{ matrix.node }} on ${{ matrix.os }}
    steps:
    - name: Tell if project is using npm or yarn
      id: step1
      uses: garronej/github_actions_toolkit@v2.4
      with: 
        action_name: tell_if_project_uses_npm_or_yarn
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-node@v2.1.3
      with:
        node-version: ${{ matrix.node }}
    - if: steps.step1.outputs.npm_or_yarn == 'yarn'
      run: |
        yarn install --frozen-lockfile                                                                                                                                                                                        
        yarn build
        yarn test:node
    - if: steps.step1.outputs.npm_or_yarn == 'npm'
      run: |
        npm ci                                                                                                                                                                                        
        npm run build
        npm test:node
  test_deno:
    runs-on: ubuntu-latest
    needs: test_lint
    name: test with Deno
    steps: 
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - name: Cache
      uses: actions/cache@v1
      with:
        path: ~/.cache/deno
        key: deno-${{ runner.os }}-${{ hashFiles('deno-lock.json') }}
        restore-keys: |
           deno-${{ runner.os }}-${{ hashFiles('deno-lock.json') }}
           deno-${{ runner.os }}-
           deno-
    - uses: denolib/setup-deno@master
      with:
        deno-version: v1.x
    - run: deno --version
    - run: |
        PACKAGE_MANAGER=npm
        if [ -f "./yarn.lock" ]; then
            PACKAGE_MANAGER=yarn
        fi
        if [ "$PACKAGE_MANAGER" = "yarn" ]; then
            yarn install --frozen-lockfile                                                                                                                                                                                        
        else
            npm ci
        fi
        $PACKAGE_MANAGER run build
        $PACKAGE_MANAGER run test:deno
  check_if_version_upgraded:
    name: Check if version upgrade
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: 
      - test_node
      - test_deno
    outputs:
      from_version: ${{ steps.step1.outputs.from_version }}
      to_version: ${{ steps.step1.outputs.to_version }}
      is_upgraded_version: ${{steps.step1.outputs.is_upgraded_version }}
    steps:
    - uses: garronej/github_actions_toolkit@v2.4
      id: step1
      with: 
        action_name: is_package_json_version_upgraded

  update_changelog:
    runs-on: ubuntu-latest
    needs: check_if_version_upgraded
    if: needs.check_if_version_upgraded.outputs.is_upgraded_version == 'true'
    steps:
    - uses: garronej/github_actions_toolkit@v2.4
      with:
        action_name: update_changelog
        branch: ${{ github.ref }}

  publish:
    runs-on: ubuntu-latest
    needs: 
      - update_changelog
      - check_if_version_upgraded
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ github.ref }}
    - run: rm -r .github
    - run: |
        git branch -d latest || true
        git push origin :latest || true
    - run: |
        git branch latest
        git checkout latest
    - uses: actions/setup-node@v2.1.3
      with:
        node-version: '15'
        registry-url: https://registry.npmjs.org/
    - run: |
        PACKAGE_MANAGER=npm
        if [ -f "./yarn.lock" ]; then
            PACKAGE_MANAGER=yarn
        fi
        if [ "$PACKAGE_MANAGER" = "yarn" ]; then
            yarn install --frozen-lockfile                                                                                                                                                                                        
        else
            npm ci
        fi
        $PACKAGE_MANAGER run build
    - run: npx -y -p denoify@0.6.5 denoify_enable_short_npm_import_path
      env:
        DRY_RUN: "0"
    - run: |
        if [ "$(npm show . version)" = "$VERSION" ]; then
          echo "This version is already published"
          exit 0
        fi
        if [ "$NODE_AUTH_TOKEN" = "" ]; then
          echo "Can't publish on NPM, You must first create a secret called NPM_TOKEN that contains your NPM auth token. https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets"
          false
        fi
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        VERSION: ${{ needs.check_if_version_upgraded.outputs.to_version }}
    - run: |
        git config --global user.name "actions"
        git config --global user.email actions@example.com
        git add -A
        git commit -am "Enabling shorter import paths"
        git push origin latest
    - name: Build GitHub release body
      id: step1
      run: |
        if [ "$FROM_VERSION" = "0.0.0" ]; then
            echo "::set-output name=body::🚀"
        else
            echo "::set-output name=body::📋 [CHANGELOG](https://github.com/$GITHUB_REPOSITORY/blob/v$TO_VERSION/CHANGELOG.md)"
        fi
      env: 
        FROM_VERSION: ${{ needs.check_if_version_upgraded.outputs.from_version }}
        TO_VERSION: ${{ needs.check_if_version_upgraded.outputs.to_version }}
    - uses: garronej/action-gh-release@v0.2.0
      with:
        name: Release v${{ needs.check_if_version_upgraded.outputs.to_version }}
        tag_name: v${{ needs.check_if_version_upgraded.outputs.to_version }}
        target_commitish: latest
        body: ${{ steps.step1.outputs.body }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
